### PR TITLE
[arcade-chat] Basic chat channels+messages flow works

### PR DESCRIPTION
**Pull request by AtlantisPleb**
[Picture of in-channel message UI](https://twitter.com/ArcadeCityHall/status/1554694358569558016)

Experimental Nostr chat support, adding message types 40 (channel create) and 42 (channel message). Envisioning that 41 will be channeljoin, and 43-4X will be various channel moderation events.

Most relevant logic is in:
- [useArcadeRelay](https://github.com/ArcadeCity/arcade/blob/8299908f1a59f09852bff1e0157025d4169b19c9/packages/use-arcade/src/hooks/useArcadeRelay.ts)
- [store](https://github.com/ArcadeCity/arcade/blob/8299908f1a59f09852bff1e0157025d4169b19c9/packages/use-arcade/src/store/index.ts)

This implementation is probably too simple, with channelId set in the content field. Should probably be a [NIP-10 tag](https://github.com/nostr-protocol/nips/blob/master/10.md)?

Open to feedback on how to restructure this to maximize interop with other event types if appropriate.

Relevant types currently:

```
export interface Channel extends NostrEvent {
  image: string
  name: string
  type: string // maybe 'public', 'private', 'geohash', 'geocoords'
}

export interface Message extends NostrEvent {
  channelId: string
  text: string // should maybe be 'content' but don't want to confuse with the event `content`
  type: string // text, image, etc...
}
```

[Link to discussion in Nostr Telegram](https://t.me/nostr_protocol/27308)

### CODE REVIEW

**Comment by fiatjaf** [comment]
What do you think of

- `kind 40, channel create`
- `kind 42, channel message, tags: ["e", <channel_create_event>]`
- `kind 43, something else, tags: ["e", <channel_create_event>]`

i.e. the channel id is the id of the channel creation event.

I don't see the need for a "channel join" event, but maybe that is useful only for cosmetic purposes.

kind 41 could be "channel metadata", similar to kind 0, but for setting a name, description etc for the channel.

**Comment by fiatjaf** [comment]
Another thing I was thinking is that it should be made clear that this is for _public channels_, since private channels would require a much more involving cryptographic protocol (that I personally am not sure it should even be done on Nostr).

**Comment by jb55** [comment]
I get channel create, but why can't channel messages be simple nip10 threads + kind1?

Seems like another missed opportunity for interoperability.

**Comment by fiatjaf** [comment]
@jb55 don't you think it is better that clients opt in to show these messages? It is easy for them to just specify `kinds: [1, 42]` instead of just `kinds: [1]`, then they can add show them in the normal feed, but with added context since they know what 42 means -- while a client that doesn't won't show completely nonsensical kind-1 messages in the normal feed.

**Comment by jb55** [comment]
yes a different kind isn't the problem. as long as chatrooms follow nip10 then it should be trivial to make it interoperate in damus.

**Comment by AtlantisPleb** [comment]
Cool - updated code [here](https://github.com/ArcadeCity/arcade/pull/30) uses NIP10 tags for channel ID and event kind 41 for channel metadata.

Will firm up the API and release a test build in a few days, then will draft a NIP and ask feedback on that.

**Comment by jb55** [comment]
ah looks like 42 are json blobs so this isn't as simple as treating type 42 notes like type 1 notes :(

I guess these will just be separate from the rest of text nostrverse for now.

**Comment by jb55** [comment]
kind 42 suggestions:

nip10 support to me would mean:

`channel_id` is a root e tag
content is just the text

**Comment by jb55** [comment]
oh looks like this is already done in https://github.com/ArcadeCity/arcade/pull/30, perhaps there are just no events like that on the relay yet?

**Comment by fiatjaf** [comment]
Yes, please, just the text!

**Pull request merged**
